name: Publish main

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ljharb/actions/node/install@main
      name: 'nvm install lts/* && npm install'
      with:
        node-version: lts/*
    - run: npm run build
    - name: Publish to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build
        clean-exclude: |
          pr
